<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P4ALAP-7172YCJ" ignored="0" name="Default test" tests="4" failures="2" timestamp="11 Feb 2018 14:07:58 GMT" time="71.135" errors="0">
  <testcase name="LoginTest" time="28.332" classname="demo.acn.internal.tests.Sample_Test_1">
    <failure type="java.lang.AssertionError" message="Login functionality failing. Expected: Login Success but Actual: Login Failure">
      <![CDATA[java.lang.AssertionError: Login functionality failing. Expected: Login Success but Actual: Login Failure
	at org.testng.Assert.fail(Assert.java:93)
	at demo.acn.internal.utilities.GenericKeywords.reportFailure(GenericKeywords.java:275)
	at demo.acn.internal.utilities.AppKeywords.verifylogin(AppKeywords.java:57)
	at demo.acn.internal.utilities.Keywords.executeKeywords(Keywords.java:58)
	at demo.acn.internal.tests.Sample_Test_1.LoginTest(Sample_Test_1.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" time="19.993" classname="demo.acn.internal.tests.Sample_Test_1"/>
  <testcase name="LoginTest" time="19.683" classname="demo.acn.internal.tests.Sample_Test_1">
    <failure type="java.lang.AssertionError" message="Login functionality failing. Expected: Login Success but Actual: Login Failure">
      <![CDATA[java.lang.AssertionError: Login functionality failing. Expected: Login Success but Actual: Login Failure
	at org.testng.Assert.fail(Assert.java:93)
	at demo.acn.internal.utilities.GenericKeywords.reportFailure(GenericKeywords.java:275)
	at demo.acn.internal.utilities.AppKeywords.verifylogin(AppKeywords.java:57)
	at demo.acn.internal.utilities.Keywords.executeKeywords(Keywords.java:58)
	at demo.acn.internal.tests.Sample_Test_1.LoginTest(Sample_Test_1.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" time="0.0" classname="demo.acn.internal.tests.Sample_Test_1">
    <skipped/>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- Default test -->
